### ISSUE TITLE
Disabled props?

### ISSUE THREAD

**Issue by arstiefel** [redbaron76/navbar-native#11]
Is there any way to have some sort of disabled prop for the buttons?

**Comment by redbaron76** [comment]
Not directly, at the moment. But you can always "simulate" it changing color/opacity in styles and applying a "mute" onPress action, as an empty callback.

**Comment by redbaron76** [comment]
@stief510 in the last release I implemented a disabled prop in order to fit your needs. Hope it will work as expected. Let me know, please.
