### ISSUE TITLE
Update react-native-vector-icons to 4.0.0 ?

### ISSUE THREAD

**Issue by hawkup** [redbaron76/navbar-native#16]
When I upgraded React Native to 0.40.0. I could not build the iOS application because [this](https://github.com/oblador/react-native-vector-icons/issues/373) problem. I had to upgrade react-native-vector-icons to 4.0.0 to fixed this.

**Comment by lucianomlima** [comment]
I send a PR with lastest versions of react-native-vector-icon and react-native-spinkit.
