### ISSUE TITLE
undefined is not an object (evaluating 'Navbar.badgeShape')

### ISSUE THREAD

**Issue by zhuanglong** [redbaron76/navbar-native#18]

**Comment by ajonno** [comment]
i just got this too, did you resolve at all ?

**Comment by zhuanglong** [comment]
Prompt error line 375, commented out

**Comment by chernandez7** [comment]
Commenting out line 375 seems to cause some instability in the module. Hopefully we can find a proper solution soon.

**Comment by felangga** [comment]
Change Navbar.badgeShape to this.badgeShape.
It work on mine 👍

**Comment by Zaki9** [comment]
getting this error after resolving badge.Shape (https://user-images.githubusercontent.com/15614463/34094008-59fd2786-e3f1-11e7-8c03-7d5ea439c84d.png)
