### ISSUE TITLE
Use with Navigator (react-native) - How to position NavBar on top of the screen?

### ISSUE THREAD

**Issue by tfreitasleal** [redbaron76/navbar-native#19]
I couldn't find an example of Navbar and Navigator.
On my App.js file (the app entry point) I have
`  render() {
    return(
        <Navigator
          initialRoute={{name: ''}}
          renderScene={this._renderScene}
          navigationBar={
            <Container>
              <Navbar
                bgColor='darkorange'
                title={"XTR App"}
                left={{
                  icon: "md-arrow-back",
                  onPress: () => {this._leftButtonAction();}
                }}
                right={[{
                  icon: "md-search",
                  onPress: () => {alert('Search!')},
                }]}
              />
            </Container>
          }
        />
    );
  }

`
but NavBar shows on the middle (vertically) of the screen. What am I doing wrong?

**Comment by redbaron76** [comment]
Probably you have some flexbox related issues with your layout.
Please follow examples provided in the README.md
