### ISSUE TITLE
Navbar is undefined error

### ISSUE THREAD

**Issue by t2n3qqq** [redbaron76/navbar-native#2]
I get an error at this point:
`static buttonShape = PropTypes.shape(Navbar.buttonPropTypes);`
`static arrayOfButtons = PropTypes.arrayOf(Navbar.buttonShape);`

Navbar is undefined inside this static fields, it works fine when I use "this" instead of classname. 
So I can't even start my app for this reason.

**Comment by wankang189** [comment]
The same problem, could you tell me how to solve

**Comment by t2n3qqq** [comment]
@wankang189 
Just change Navbar classname on 'this' keyword in your node_modules/navbar-native/components/navbar.js. Like this #5
